# Project information
site_name: Personal Growth
site_description: Personal Growth（个人成长）
site_author: HyperJ
site_url: https://github.com/hyperj/talk.growth

# Repository
repo_name: hyperj/talk.growth
repo_url: https://github.com/hyperj/talk.growth
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2009 - 2018 HyperJ'

# Configuration
theme:
  name: 'material'

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/hyperj-black.png
  logo: assets/images/hyperj.png

# Customization
extra:
  social:
    - type: github-alt
      link: https://gist.github.com/hyperj/
    - type: github
      link: https://github.com/hyperj
    - type: h-square
      link: http://blog.hyperj.net
    - type: linkedin
      link: https://www.linkedin.com/in/hyperj

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - TODO: todo.md
  - Life: life.md
  - Book: book.md
  - Work: work.md
  - Rule: rule.md
  - Quote: quote.md
  - Learn: learn.md
  - Experience: experience.md

# Analytics


