# Project information
site_name: 成长学习笔记
site_description: 成长学习笔记
site_author: HyperJ
site_url: https://hyperj.net/talk.growth

# Repository
repo_name: hyperj/talk.growth
repo_url: https://github.com/hyperj/talk.growth
edit_uri: blob/master/docs

# Copyright
copyright: Copyright &copy; 2013 - <span id="cyear">2013</span> HyperJ <script type="text/javascript">document.getElementById("cyear").innerText=new Date().getFullYear();document.write(unescape("%3Cdiv id='cnzz_stat_icon_1275779234'%3E%3C/div%3E%3Cscript src='https://s5.cnzz.com/z_stat.php%3Fid%3D1275779234%26online%3D1%26show%3Dline' type='text/javascript'%3E%3C/script%3E"));</script>

# Configuration
theme:
  name: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: true
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: white
    accent: amber
  font:
    text: Roboto
    code: Roboto Mono
  favicon: /assets/images/hyperj.ico
  logo: /assets/images/hyperj.png

# Customization
extra:
  social:
    - type: h-square
      link: https://hyperj.net
    - type: github
      link: https://github.com/hyperj
    - type: linkedin
      link: https://www.linkedin.com/in/hyperj

extra_css:
  - /assets/css/mkdocs/material.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - 主页: index.md
  - 工作:
    - 工作: work.md
  - 学习:
    - 阅读: book.md
    - 规则: rule.md
    - 得到:
      - 《逻辑思维 - 罗胖》: igetget/logical-thinking.md
      - 《精英日课 - 万维钢》: igetget/elite-day-class.md
      - 《清华管理学课 - 宁向东》: igetget/tsinghua-management-course.md
      - 《北大领导力30讲 - 刘澜》: igetget/peking-university-leadership-30-lectures.md
      - 《怎样成为精力管理的高手 - 张遇升》: igetget/how-to-become-a-master-of-energy-management.md
      - 《老喻的人生算法课 - 喻颖正》: igetget/life-algorithm-class.md
    - 极客时间:
      - 《数据结构与算法之美 - 王争》: geekbang/the-beauty-of-data-structures-and-algorithms.md
      - 《人工智能基础课 - 王天一》: geekbang/artificial-intelligence-basic-course.md
      - 《机器学习 - 王天一》: geekbang/machine-learning.md
      - 《Java核心技术36讲 - 杨晓峰》: geekbang/java-core-technology.md
      - 《深入拆解Java虚拟机 - 郑雨迪》: geekbang/deep-dive-into-java-virtual-machine.md
  - 生活:
    - 生活: life.md
    - 引用: quote.md

# Analytics


